travis:
  secure:
    BINSTAR_TOKEN: MFtoVrDkNxH9kxpkuQXy9dOII98GW4MlvXvo0f4P+S0v2QozGHlf8NrTtEsFx/hIrzK9iJ1PQE7Pf19FeIDDvRkaFU9TvERHzmq1Z//XZ4neRWEx+dsrrTbR8V1L7WTOphbCA+XON2szvD5fXku/exIqq6FY4IZjrz0A+k2AAnCMXlDqqUBj1CEPCTdr4OewQQwvDkaL9PUj7JIxBgmpg/yxCLmdYGQIVWuKIbqpw+BD/lWXpxrzeoUJeO6td7hwWNmFjwuH+XqSL69cL6MUzssn+ceyozeFiVN7QK3K1JtISK652H5fFVvOnBfphvXRJYMHdsqfJrGRSi//b/LYuLOipDbOdP+RK6rNu/ktj2BSerI68LonSA7DOQo/6IkIPpwg5xd0eAadPBnFwedLl2IeYAkkMnJ742epxJ/grPJEpJK0eYZr9ksKMir1UdS9h0utbmjMljEWy3AIJsC8FFBc9A+OU5ymmJPClTC3N1DpYQMW26qJlm24gG4+QmLolo8uujUKNrL7FqwzFVzgkVCDnDk/g8d10tVtSP8ZPDY2/lk9pcwvjwC+NmfgXMZRW43nmi/j8lUBvPiEVJLExd5vJ5ynz+gwCTgSwTAsCzo5f6K9lPmiL9bFGsSvMLz0CICo5MUMHBNXIrN8DeWlEVczS5SN69+UruWZLzXyUu0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
