travis:
  secure:
    BINSTAR_TOKEN: LbVbr72H9+lY1AG6ItwOe+wRSzBPQEDmsbvy5CCdnUSIrt9tFSn4uLB5DfuNGQqjQ36nPq6wXsIAH+c2Xh0VNIdJ32+owwXEjisozx8lLOAjcnA9hwp1inCWaZ8iLGJU5DgJk9lTUe1Frk6HKHm8nmQ4DlgvWKdtUbcjdGUQY7fqJx2I+X1APhp77KN6m8GOdxB2DWAFWC1IFSyAzwXZXsQGYXI1eWlKgeoXVt5D7OSNwIugEBZJ/I7O6FrA42hDI8/wVLXJ3xhprcn6fkQfHOHawoAS5yK65Q120MUVzdiGicbaH0Ag1eAws9wWVpsppjMxTgYbVPX8OZ6s5yCsmAG3OjZez7Na9zxQ7GEILzX6kDOECKK476thrV1HxJdUV8pfzPP/FocmG1M9N6v6jXOwX9pjmEOEjNUbndPkuwsi4lcI2d5FKo7Y539vlqqB1CXAQO27Z9zhq33tm400WNROkkvuSzOzpRzDg9QAhBlMB07DO1EGUWz6vSBvxlDZy+o2nBRP78hR4JuHi3kJCHfu7qDV7r+Y55DUscQN4v6jkIz1uyvI9MlTpB1KcJwMYH+hRJ+IRatqxru84fesPbCV1qbyOUe3nZxqiFHdSVc9un2jzZddNdvOSmWKdS1LCIkqsulj7gJtR5zy0abfkbFqZks3tiLGbuhyjTRM+Eo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
